package rules

import (
	"fmt"
	"regexp"
	"strings"
)

// Sender classes returned by SenderClass.
const (
	ClassHuman         = "human"         // written by a person to a person
	ClassTransactional = "transactional" // machine-generated, but for this recipient specifically
	ClassBulk          = "bulk"          // marketing or newsletter sent to a list
	ClassList          = "list"          // relayed by a mailing list
	ClassAutomated     = "automated"     // system notification, bounce, or auto-reply
	ClassUnknown       = "unknown"       // not enough signal to decide
)

// HumanSignal is one piece of evidence for or against a message having been
// typed by a person.
type HumanSignal struct {
	Name    string  // stable identifier
	Weight  float64 // positive favours human, negative favours automated
	Present bool
	Detail  string
}

// HumanAssessment is the full result of human-versus-machine analysis.
type HumanAssessment struct {
	// Score runs from 0 (certainly machine-generated) to 100 (almost
	// certainly typed by a person).
	Score float64
	Class string
	// Signals lists every signal that fired, strongest evidence first.
	Signals []HumanSignal
	// Reasons is a human-readable summary of the firing signals.
	Reasons []string
}

// bulkHeaders are fields that only appear on machine-generated mail.
var bulkHeaders = []string{
	"List-Unsubscribe", "List-Id", "List-Post", "List-Help", "List-Owner",
	"List-Archive", "List-Subscribe", "Feedback-ID", "X-Campaign-Id",
	"X-Campaignid", "X-Mailchimp-Id", "X-MC-User", "X-SG-EID", "X-SES-Outgoing",
	"X-Mailgun-Sid", "X-Mandrill-User", "X-Sendgrid-Eid", "X-CSA-Complaints",
	"X-Report-Abuse", "X-Marketing-Campaign", "X-Bulkmail", "X-Mailer-Lid",
	"X-Constantcontact-Id", "X-Klaviyo-Message-Id", "X-Sfmc-Stack",
	"X-Job", "X-Rpcampaign", "X-Emarsys-Id", "X-Braze-Id",
}

// autoSubmittedHeaders indicate the message was generated in response to
// something rather than composed.
var autoSubmittedHeaders = []string{
	"Auto-Submitted", "X-Auto-Response-Suppress", "X-Autoreply",
	"X-Autorespond", "X-Autogenerated", "X-Auto-Generated",
	"X-Failed-Recipients", "X-Autoreply-From",
}

// humanMailers are User-Agent and X-Mailer values produced by mail clients a
// person composes in, as opposed to sending libraries and campaign platforms.
var humanMailers = []string{
	"apple mail", "iphone mail", "ipad mail", "mimestream",
	"thunderbird", "mozilla", "outlook", "microsoft outlook",
	"airmail", "spark", "mailmate", "postbox", "em client",
	"evolution", "kmail", "claws mail", "mutt", "neomutt", "alpine",
	"gnus", "roundcube", "bluemail", "canary", "edison",
	"windows mail", "yahoo mail", "zoho mail", "protonmail", "hey",
	"superhuman", "missive", "front", "newton", "polymail",
}

// bulkMailers are sending platforms and libraries.
var bulkMailers = []string{
	"mailchimp", "sendgrid", "mailgun", "amazonses", "amazon ses",
	"sparkpost", "postmark", "mandrill", "constant contact", "klaviyo",
	"campaign monitor", "salesforce", "marketo", "hubspot", "pardot",
	"emarsys", "braze", "iterable", "customer.io", "sendinblue", "brevo",
	"phplist", "phpmailer", "swiftmailer", "nodemailer", "python-requests",
	"smtplib", "javamail", "actionmailer", "zend_mail", "drupal", "wordpress",
	"mailer-daemon", "cron", "logwatch", "nagios", "zabbix", "jenkins",
	"gitlab", "github", "jira", "confluence", "pagerduty", "opsgenie",
}

// noReplyPattern matches local parts that announce the mailbox is unattended.
var noReplyPattern = regexp.MustCompile(`(?i)^(no[-_.]?reply|do[-_.]?not[-_.]?reply|donotreply|noreply|notifications?|alerts?|mailer[-_.]?daemon|postmaster|bounces?|auto(mated)?|system|robot|bot|daemon|nobody|support[-_.]?bot)([-_.+].*)?$`)

// verpPattern matches variable envelope return paths and SRS-rewritten
// senders, both of which are generated per-recipient by bulk senders.
var verpPattern = regexp.MustCompile(`(?i)(^srs\d=|^bounces?[-+]|[-+]bounces?[-+@=]|^prvs=|^msprvs\d?=|=.*=@|\+caf_)`)

// templateMarkers are placeholder syntaxes left behind by broken merges, and
// the boilerplate that only appears in bulk mail.
var templateMarkers = []string{
	"%%", "{{", "}}", "*|", "|*", "${", "[[", "]]",
	"view in browser", "view this email in your browser",
	"unsubscribe", "manage preferences", "email preferences",
	"you are receiving this", "you're receiving this",
	"update your preferences", "opt out", "privacy policy",
	"this is an automated message", "do not reply to this",
	"please do not reply", "automated notification",
}

// replySubjectPattern matches the reply and forward prefixes used across
// locales.
var replySubjectPattern = regexp.MustCompile(`(?i)^\s*((re|fw|fwd|aw|sv|vs|antw|res|odp|ynt|tr|rif|enc)\s*(\[\d+\])?\s*:\s*)+`)

// AssessHuman evaluates whether a message was composed by a person and
// returns the score, class and supporting evidence.
//
// The scoring is deliberately evidence-based rather than a single threshold:
// a message can be transactional (machine-written but individually addressed)
// without being bulk, and the caller usually wants that distinction.
func (m *MessageContext) AssessHuman() *HumanAssessment {
	var signals []HumanSignal

	fire := func(name string, weight float64, present bool, detail string) {
		if present {
			signals = append(signals, HumanSignal{Name: name, Weight: weight, Present: true, Detail: detail})
		}
	}

	from := ParseAddress(m.Get("From"))
	subject := m.Get("Subject")
	text := m.SearchText()
	lowerText := strings.ToLower(text)

	// -- Signals that the message is machine-generated ----------------------

	var presentBulk []string
	for _, h := range bulkHeaders {
		if m.Has(h) {
			presentBulk = append(presentBulk, h)
		}
	}
	fire("bulk_headers", -30, len(presentBulk) > 0,
		"bulk-mail headers present: "+strings.Join(presentBulk, ", "))

	precedence := strings.ToLower(strings.TrimSpace(m.Get("Precedence")))
	fire("precedence_bulk", -25,
		precedence == "bulk" || precedence == "list" || precedence == "junk",
		fmt.Sprintf("Precedence: %s", precedence))

	autoSubmitted := strings.ToLower(strings.TrimSpace(m.Get("Auto-Submitted")))
	fire("auto_submitted", -30,
		autoSubmitted != "" && autoSubmitted != "no",
		fmt.Sprintf("Auto-Submitted: %s", autoSubmitted))

	var presentAuto []string
	for _, h := range autoSubmittedHeaders {
		if h == "Auto-Submitted" {
			continue
		}
		if m.Has(h) {
			presentAuto = append(presentAuto, h)
		}
	}
	fire("auto_headers", -20, len(presentAuto) > 0,
		"auto-generation headers present: "+strings.Join(presentAuto, ", "))

	fire("noreply_sender", -25, noReplyPattern.MatchString(from.Local),
		fmt.Sprintf("sender local part %q is an unattended mailbox", from.Local))

	envelope := m.envelopeSender()
	fire("verp_envelope", -15,
		envelope != "" && verpPattern.MatchString(envelope),
		fmt.Sprintf("envelope sender %q is per-recipient encoded", envelope))

	mailer := strings.ToLower(m.Get("X-Mailer") + " " + m.Get("User-Agent"))
	matchedBulkMailer := ""
	for _, b := range bulkMailers {
		if strings.Contains(mailer, b) {
			matchedBulkMailer = b
			break
		}
	}
	fire("bulk_mailer", -20, matchedBulkMailer != "",
		fmt.Sprintf("sending software identifies as %q", matchedBulkMailer))

	pixels := m.TrackingPixelCount()
	fire("tracking_pixel", -20, pixels > 0,
		fmt.Sprintf("%d tracking pixel(s) in the HTML part", pixels))

	var matchedMarkers []string
	for _, marker := range templateMarkers {
		if strings.Contains(lowerText, marker) {
			matchedMarkers = append(matchedMarkers, marker)
		}
	}
	fire("template_markers", -15, len(matchedMarkers) > 0,
		fmt.Sprintf("bulk-mail boilerplate found: %s", strings.Join(matchedMarkers, ", ")))

	// HTML with no plain-text alternative is characteristic of a campaign
	// tool; human clients that send HTML almost always send multipart.
	fire("html_only", -12, m.HTMLBody != "" && strings.TrimSpace(m.TextBody) == "",
		"message is HTML-only with no text/plain alternative")

	urls := m.URLs()
	fire("many_links", -12, len(urls) >= 8,
		fmt.Sprintf("%d links in the body", len(urls)))

	recipients := len(ParseAddressList(m.Get("To"))) + len(ParseAddressList(m.Get("Cc")))
	fire("undisclosed_recipients", -10,
		recipients == 0 && m.Get("To") != "",
		"To field names no parseable recipient")

	fire("bulk_precedence_class", -10,
		m.Has("X-Priority") && m.Has("List-Unsubscribe"),
		"campaign-style priority and unsubscribe headers together")

	// -- Signals that a person composed the message -------------------------

	inReplyTo := m.Has("In-Reply-To")
	references := m.Has("References")
	fire("threaded", 30, inReplyTo || references,
		"message is part of a thread (In-Reply-To or References present)")

	fire("reply_subject", 15, replySubjectPattern.MatchString(subject),
		fmt.Sprintf("Subject carries a reply or forward prefix: %q", TruncateRunes(subject, 40)))

	matchedHumanMailer := ""
	for _, h := range humanMailers {
		if strings.Contains(mailer, h) {
			matchedHumanMailer = h
			break
		}
	}
	fire("human_mailer", 25, matchedHumanMailer != "" && matchedBulkMailer == "",
		fmt.Sprintf("sending software is an interactive mail client (%q)", matchedHumanMailer))

	fire("few_recipients", 10, recipients >= 1 && recipients <= 3,
		fmt.Sprintf("%d named recipient(s)", recipients))

	fire("has_plain_text", 8, strings.TrimSpace(m.TextBody) != "",
		"message has a text/plain part")

	fire("no_links", 10, len(urls) == 0 && len(text) > 0,
		"body contains no links")

	// A signature block or a quoted reply is hard to fake incidentally.
	fire("quoted_reply", 15,
		strings.Contains(text, "\n> ") || strings.Contains(lowerText, "wrote:") ||
			strings.Contains(lowerText, "-----original message-----"),
		"body contains quoted text from an earlier message")

	fire("msgid_aligned", 5,
		msgIDAligned(m),
		"Message-ID domain matches the From domain")

	fire("personal_greeting", 8, hasPersonalGreeting(lowerText),
		"body opens with a personal greeting")

	// -- Aggregate ----------------------------------------------------------

	assessment := &HumanAssessment{Signals: signals}

	// Start neutral and let the evidence move the score. Clamping at the ends
	// keeps a pile-on of weak signals from saturating the scale.
	raw := 50.0
	for _, s := range signals {
		raw += s.Weight
	}
	assessment.Score = clampFloat(raw, 0, 100)

	for _, s := range signals {
		assessment.Reasons = append(assessment.Reasons,
			fmt.Sprintf("%+.0f %s: %s", s.Weight, s.Name, s.Detail))
	}

	assessment.Class = m.classify(assessment, recipients)
	return assessment
}

// classify assigns a sender class from the assessment and the message shape.
// The order matters: a mailing list relaying a human-written post is still a
// list, and a bounce is automated regardless of how personal it reads.
func (m *MessageContext) classify(a *HumanAssessment, recipients int) string {
	if m.isDiscussionList() {
		return ClassList
	}

	autoSubmitted := strings.ToLower(strings.TrimSpace(m.Get("Auto-Submitted")))
	if (autoSubmitted != "" && autoSubmitted != "no") ||
		m.envelopeSender() == "" && m.Has("X-Failed-Recipients") {
		return ClassAutomated
	}

	from := ParseAddress(m.Get("From"))
	unattended := noReplyPattern.MatchString(from.Local)

	hasBulkMarkers := false
	for _, h := range bulkHeaders {
		if m.Has(h) {
			hasBulkMarkers = true
			break
		}
	}
	if hasBulkMarkers || m.TrackingPixelCount() > 0 {
		return ClassBulk
	}

	if a.Score >= 65 {
		return ClassHuman
	}

	// Machine-written but addressed to this recipient alone, with no campaign
	// infrastructure behind it: a receipt, a password reset, an alert.
	if unattended && recipients >= 1 && recipients <= 2 {
		return ClassTransactional
	}

	if a.Score <= 30 {
		return ClassAutomated
	}
	if a.Score <= 45 {
		return ClassTransactional
	}
	return ClassUnknown
}

// IsHuman reports whether the message looks like it was typed by a person.
func (m *MessageContext) IsHuman() bool {
	return m.AssessHuman().Class == ClassHuman
}

// IsAutomated reports whether the message was machine-generated in any form,
// including bulk, list and transactional mail.
func (m *MessageContext) IsAutomated() bool {
	switch m.AssessHuman().Class {
	case ClassHuman, ClassUnknown:
		return false
	}
	return true
}

// IsBulk reports whether the message was sent to a list rather than composed
// for the recipient.
func (m *MessageContext) IsBulk() bool {
	class := m.AssessHuman().Class
	return class == ClassBulk || class == ClassList
}

func msgIDAligned(m *MessageContext) bool {
	raw := strings.Trim(strings.TrimSpace(m.Get("Message-ID")), "<>")
	at := strings.LastIndex(raw, "@")
	if at < 0 {
		return false
	}
	return SameOrgDomain(raw[at+1:], DomainOf(m.Get("From")))
}

var greetingPattern = regexp.MustCompile(`(?i)^\s*(hi|hey|hello|dear|good (morning|afternoon|evening)|greetings)\b[^\n]{0,40}(,|!|\n)`)

func hasPersonalGreeting(lowerText string) bool {
	trimmed := strings.TrimSpace(lowerText)
	if len(trimmed) > 200 {
		trimmed = trimmed[:200]
	}
	if !greetingPattern.MatchString(trimmed) {
		return false
	}
	// "Dear Customer" and "Hi there" are bulk-mail salutations, not personal.
	for _, generic := range []string{"customer", "valued", "user", "member", "subscriber", "there", "sir or madam", "friend"} {
		if strings.Contains(trimmed[:minInt(len(trimmed), 60)], generic) {
			return false
		}
	}
	return true
}

func clampFloat(v, lo, hi float64) float64 {
	if v < lo {
		return lo
	}
	if v > hi {
		return hi
	}
	return v
}
