// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v7.35.1
// source: pkg/proto/mailscript.proto

package mailscriptpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	MailScriptService_ProcessMessage_FullMethodName       = "/mailscript.MailScriptService/ProcessMessage"
	MailScriptService_GetStats_FullMethodName             = "/mailscript.MailScriptService/GetStats"
	MailScriptService_Health_FullMethodName               = "/mailscript.MailScriptService/Health"
	MailScriptService_ProcessMessageStream_FullMethodName = "/mailscript.MailScriptService/ProcessMessageStream"
)

// MailScriptServiceClient is the client API for MailScriptService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MailScriptServiceClient interface {
	// Process a message through MailScript rules
	ProcessMessage(ctx context.Context, in *ProcessRequest, opts ...grpc.CallOption) (*ProcessResponse, error)
	// Get proxy statistics
	GetStats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error)
	// Health check
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// Stream message processing (for high throughput)
	ProcessMessageStream(ctx context.Context, opts ...grpc.CallOption) (MailScriptService_ProcessMessageStreamClient, error)
}

type mailScriptServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMailScriptServiceClient(cc grpc.ClientConnInterface) MailScriptServiceClient {
	return &mailScriptServiceClient{cc}
}

func (c *mailScriptServiceClient) ProcessMessage(ctx context.Context, in *ProcessRequest, opts ...grpc.CallOption) (*ProcessResponse, error) {
	out := new(ProcessResponse)
	err := c.cc.Invoke(ctx, MailScriptService_ProcessMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailScriptServiceClient) GetStats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error) {
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, MailScriptService_GetStats_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailScriptServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, MailScriptService_Health_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailScriptServiceClient) ProcessMessageStream(ctx context.Context, opts ...grpc.CallOption) (MailScriptService_ProcessMessageStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &MailScriptService_ServiceDesc.Streams[0], MailScriptService_ProcessMessageStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &mailScriptServiceProcessMessageStreamClient{stream}
	return x, nil
}

type MailScriptService_ProcessMessageStreamClient interface {
	Send(*ProcessRequest) error
	Recv() (*ProcessResponse, error)
	grpc.ClientStream
}

type mailScriptServiceProcessMessageStreamClient struct {
	grpc.ClientStream
}

func (x *mailScriptServiceProcessMessageStreamClient) Send(m *ProcessRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *mailScriptServiceProcessMessageStreamClient) Recv() (*ProcessResponse, error) {
	m := new(ProcessResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MailScriptServiceServer is the server API for MailScriptService service.
// All implementations must embed UnimplementedMailScriptServiceServer
// for forward compatibility
type MailScriptServiceServer interface {
	// Process a message through MailScript rules
	ProcessMessage(context.Context, *ProcessRequest) (*ProcessResponse, error)
	// Get proxy statistics
	GetStats(context.Context, *StatsRequest) (*StatsResponse, error)
	// Health check
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	// Stream message processing (for high throughput)
	ProcessMessageStream(MailScriptService_ProcessMessageStreamServer) error
	mustEmbedUnimplementedMailScriptServiceServer()
}

// UnimplementedMailScriptServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMailScriptServiceServer struct {
}

func (UnimplementedMailScriptServiceServer) ProcessMessage(context.Context, *ProcessRequest) (*ProcessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessMessage not implemented")
}
func (UnimplementedMailScriptServiceServer) GetStats(context.Context, *StatsRequest) (*StatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedMailScriptServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedMailScriptServiceServer) ProcessMessageStream(MailScriptService_ProcessMessageStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method ProcessMessageStream not implemented")
}
func (UnimplementedMailScriptServiceServer) mustEmbedUnimplementedMailScriptServiceServer() {}

// UnsafeMailScriptServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MailScriptServiceServer will
// result in compilation errors.
type UnsafeMailScriptServiceServer interface {
	mustEmbedUnimplementedMailScriptServiceServer()
}

func RegisterMailScriptServiceServer(s grpc.ServiceRegistrar, srv MailScriptServiceServer) {
	s.RegisterService(&MailScriptService_ServiceDesc, srv)
}

func _MailScriptService_ProcessMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailScriptServiceServer).ProcessMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MailScriptService_ProcessMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailScriptServiceServer).ProcessMessage(ctx, req.(*ProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailScriptService_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailScriptServiceServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MailScriptService_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailScriptServiceServer).GetStats(ctx, req.(*StatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailScriptService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailScriptServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MailScriptService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailScriptServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailScriptService_ProcessMessageStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MailScriptServiceServer).ProcessMessageStream(&mailScriptServiceProcessMessageStreamServer{stream})
}

type MailScriptService_ProcessMessageStreamServer interface {
	Send(*ProcessResponse) error
	Recv() (*ProcessRequest, error)
	grpc.ServerStream
}

type mailScriptServiceProcessMessageStreamServer struct {
	grpc.ServerStream
}

func (x *mailScriptServiceProcessMessageStreamServer) Send(m *ProcessResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *mailScriptServiceProcessMessageStreamServer) Recv() (*ProcessRequest, error) {
	m := new(ProcessRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MailScriptService_ServiceDesc is the grpc.ServiceDesc for MailScriptService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MailScriptService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mailscript.MailScriptService",
	HandlerType: (*MailScriptServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessMessage",
			Handler:    _MailScriptService_ProcessMessage_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _MailScriptService_GetStats_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _MailScriptService_Health_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ProcessMessageStream",
			Handler:       _MailScriptService_ProcessMessageStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/proto/mailscript.proto",
}
